export { default as Input } from "./Input";
export { default as FormContainer } from "./FormContainer";
export { default as SectionForm } from "./SectionForm";
export { default as Button } from "./Button";
export { default as Text } from "./Text";
export { default as Header } from "./Header";
export { default as SubHeader } from "./SubHeader";
export { default as ContenedorEstandar } from "./ContenedorEstandar";
export { default as Titulo } from "./Titulo";
